# Generated by Django 3.1.2 on 2020-11-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='Dish',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
    ]
