# Generated by Django 3.1.2 on 2020-11-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201102_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
    ]
