# Generated by Django 3.1.2 on 2020-11-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20201102_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['week_id']},
        ),
    ]
