# Generated by Django 3.1.2 on 2020-11-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20201102_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(default='day 1 content', max_length=256)),
                ('day2', models.CharField(default='day 2 content', max_length=256)),
                ('day3', models.CharField(default='day 3 content', max_length=256)),
                ('day4', models.CharField(default='day 4 content', max_length=256)),
                ('day5', models.CharField(default='day 5 content', max_length=256)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='src.content')),
            ],
            options={
                'db_table': 'days',
            },
        ),
    ]
